.pull-cache:
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - .gradle

image: azul/zulu-openjdk:14

stages:
  - build
  - test
  - deploy

variables:
  GRADLE_OPTS: '-Dorg.gradle.daemon=false -Dorg.gradle.caching=true -Dorg.gradle.parallel=true -Dorg.gradle.jvmargs="-Xmx4g -XX:MaxMetaspaceSize=1g"'

build:
  stage: build
  script:
    - ./ci-build.sh
  after_script:
    - ./ci-gradle-cleanup.sh
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - build
      - .gradle

.test:
  stage: test
  extends:
    - .pull-cache
  script:
    - ./ci-test.sh
  after_script:
    - ./ci-gradle-cleanup.sh
  artifacts:
    when: always
    reports:
      junit: "**/build/test-results/test/**/TEST-*.xml"
  needs:
    - build

deploy:
  stage: deploy
  extends:
    - .pull-cache
  script:
    - ./ci-deploy.sh
  after_script:
    - ./ci-gradle-cleanup.sh
