include:
  - local: '.gitlab-ci/kuberig-dsl-kubernetes.yml'
  - local: '.gitlab-ci/kuberig-dsl-openshift.yml'

.cache:
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    policy: pull-push
    paths:
      - /builds/kuberig/kuberig-dsl/kuberig-dsl/build
      - /builds/kuberig/kuberig-dsl/kuberig-dsl-generator/build
      - /builds/kuberig/kuberig-dsl/kuberig-dsl-generator-gradle-plugin/build
      - /builds/kuberig/kuberig-dsl/.gradle
      - /builds/kuberig/.gradle

image: gradle:6.8.3-jdk15-hotspot

stages:
  - build
  - deploy
  - dsls

kuberig-dsl-build:
  stage: build
  tags:
    - bm
  extends:
    - .cache
  script:
    - ./ci-gradle.sh version build
    - bash <(curl -s https://codecov.io/bash)
  artifacts:
    when: always
    reports:
      junit: "**/build/test-results/test/**/TEST-*.xml"

kuberig-dsl-deploy:
  stage: deploy
  tags:
    - bm
  extends:
    - .cache
  script:
    - ./ci-gradle.sh version publishToMavenLocal
  needs:
    - kuberig-dsl-build
