.cache:
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    policy: pull-push
    paths:
      - /builds/kuberig/kuberig-dsl/kuberig-dsl/build
      - /builds/kuberig/kuberig-dsl/kuberig-dsl-generator/build
      - /builds/kuberig/kuberig-dsl/kuberig-dsl-generator-gradle-plugin/build
      - /builds/kuberig/kuberig-dsl/.gradle
      - /builds/kuberig/.gradle

image: gradle:6.8.3-jdk15-hotspot

stages:
  - build
  - deploy
  - dsls

kuberig-dsl-build:
  stage: build
  tags:
    - bm
  extends:
    - .cache
  script:
    - ./ci-gradle.sh version build
    - bash <(curl -s https://codecov.io/bash)
  artifacts:
    when: always
    reports:
      junit: "**/build/test-results/test/**/TEST-*.xml"

kuberig-dsl-deploy:
  stage: deploy
  tags:
    - bm
  extends:
    - .cache
  script:
    - ./ci-gradle.sh version publishToMavenLocal
  needs:
    - kuberig-dsl-build

kuberig-dsl-kubernetes:
  stage: dsls
  needs:
    - kuberig-dsl-deploy
  script:
    - |
      cd kuberig-dsl/vanilla-dsls/kuberig-dsl-kubernetes/kuberig-dsl-kubernetes-${KUBERNETES_VERSION}
      ./gradlew publishToMavenLocal
  parallel:
    matrix:
      - KUBERNETES_VERSION:
          - v1.14.10
          - v1.15.0
          - v1.15.1
          - v1.15.10
          - v1.15.11
          - v1.15.12
          - v1.15.2
          - v1.15.3
          - v1.15.4
          - v1.15.5
          - v1.15.6
          - v1.15.7
          - v1.15.8
          - v1.15.9
          - v1.16.0
          - v1.16.1
          - v1.16.10
          - v1.16.11
          - v1.16.12
          - v1.16.13
          - v1.16.14
          - v1.16.15
          - v1.16.2
          - v1.16.3
          - v1.16.4
          - v1.16.5
          - v1.16.6
          - v1.16.7
          - v1.16.8
          - v1.16.9
          - v1.17.0
          - v1.17.1
          - v1.17.10
          - v1.17.11
          - v1.17.12
          - v1.17.13
          - v1.17.14
          - v1.17.15
          - v1.17.16
          - v1.17.17
          - v1.17.2
          - v1.17.3
          - v1.17.4
          - v1.17.5
          - v1.17.6
          - v1.17.7
          - v1.17.8
          - v1.17.9
          - v1.18.0
          - v1.18.1
          - v1.18.10
          - v1.18.11
          - v1.18.12
          - v1.18.13
          - v1.18.14
          - v1.18.15
          - v1.18.16
          - v1.18.17
          - v1.18.2
          - v1.18.3
          - v1.18.4
          - v1.18.5
          - v1.18.6
          - v1.18.7
          - v1.18.8
          - v1.18.9
          - v1.19.0
          - v1.19.1
          - v1.19.2
          - v1.19.3
          - v1.19.4
          - v1.19.5
          - v1.19.6
          - v1.19.7
          - v1.19.8
          - v1.19.9
          - v1.20.0
          - v1.20.1
          - v1.20.2
          - v1.20.3
          - v1.20.4
          - v1.20.5

kuberig-dsl-openshift:
  stage: dsls
  needs:
    - kuberig-dsl-deploy
  script:
    - |
      cd kuberig-dsl/vanilla-dsls/kuberig-dsl-openshift/kuberig-dsl-openshift-${OPENSHIFT_VERSION}
      ./ci-gradle.sh publishToMavenLocal
  parallel:
    matrix:
      - OPENSHIFT_VERSION:
          - v3.9.0
          - v3.10.0
          - v3.11.0
          - v4.1.0
          - v4.2.0
          - v4.3.0
          - v4.4.0
          - v4.5.0
          - v4.6.0