include:
  - local: '/kuberig-dsl/vanilla-dsls/.gitlab-ci.yml'

.cache:
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    policy: pull-push
    paths:
      - build
      - .gradle

image: gradle:6.8.3-jdk15-hotspot

stages:
  - build
  - deploy
  - dsls

build:
  stage: build
  extends:
    - .cache
  script:
    - ./ci-gradle.sh version build
    - bash <(curl -s https://codecov.io/bash)
  after_script:
    - ./ci-gradle-cleanup.sh
  artifacts:
    when: always
    reports:
      junit: "**/build/test-results/test/**/TEST-*.xml"

deploy:
  stage: deploy
  extends:
    - .cache
  script:
    - ./ci-gradle.sh version publishToMavenLocal
  after_script:
    - ./ci-gradle-cleanup.sh
