.pull-cache:
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - .gradle

image: gradle:6.8.2-jdk15-hotspot

stages:
  - build
  - test
  - deploy

variables:
  GRADLE_OPTS: '-Dorg.gradle.daemon=false -Dorg.gradle.caching=true -Dorg.gradle.parallel=true -Dorg.gradle.jvmargs="-Xmx4g -XX:MaxMetaspaceSize=1g"'

before_script:
  - |
    export GRADLE_USER_HOME=`pwd`/.gradle
    echo $M2_SIGNING_KEY | base64 -d > ~/m2_signing_key.pgp
    export ORG_GRADLE_PROJECT_signing_secretKeyRingFile=~/m2_signing_key.pgp

build:
  stage: build
  script:
    - |
      gradle assemble
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - build
      - .gradle

test:
  stage: test
  extends:
    - .pull-cache
  script:
    - |
      gradle check
      bash <(curl -s https://codecov.io/bash)
  artifacts:
    when: always
    reports:
      junit: "**/build/test-results/test/**/TEST-*.xml"
  needs:
    - build

deploy:
  stage: deploy
  extends:
    - .pull-cache
  script:
    - |
      gradle deploy
  needs:
    - test
