.pull-cache:
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - .gradle

# This is the Gradle build system for JVM applications
# https://gradle.org/
# https://github.com/gradle/gradle
image: gradle:6.8.2-jdk15-hotspot

stages:
  - build
  - test
  - deploy

# Disable the Gradle daemon for Continuous Integration servers as correctness
# is usually a priority over speed in CI environments. Using a fresh
# runtime for each build is more reliable since the runtime is completely
# isolated from any previous builds.
variables:
  JVM_OPTS: "-Xmx4g"
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

# Feature / Pull-Request builds
build:
  stage: build
  script: gradle --build-cache assemble
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - build
      - .gradle

test:
  stage: test
  extends:
    - .pull-cache
  script:
    - |
      gradle check
      bash <(curl -s https://codecov.io/bash)
  artifacts:
    when: always
    reports:
      junit: "**/build/test-results/test/**/TEST-*.xml"
  needs:
    - build

deploy:
  stage: deploy
  extends:
    - .pull-cache
  script:
    - |
      echo $M2_SIGNING_KEY | base64 -d > ~/m2_signing_key.pgp
      export ORG_GRADLE_PROJECT_signing_secretKeyRingFile=~/m2_signing_key.pgp
      gradle deploy
  needs:
    - test
