image: azul/zulu-openjdk:14

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - ./ci-gradle.sh assemble
  after_script:
    - ./ci-gradle-cleanup.sh

.test:
  stage: test
  script:
    - ./ci-gradle.sh test
    - bash <(curl -s https://codecov.io/bash)
  after_script:
    - ./ci-gradle-cleanup.sh
  artifacts:
    when: always
    reports:
      junit: "**/build/test-results/test/**/TEST-*.xml"
  needs:
    - build

deploy:
  stage: deploy
  script:
    - ./ci-gradle.sh deploy -x test
  after_script:
    - ./ci-gradle-cleanup.sh
