.cache:
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    policy: pull-push
    paths:
      - build
      - .gradle

image: gradle:6.8.3-jdk15-hotspot

stages:
  - build
  - test
  - deploy

build:
  stage: build
  extends:
    - .cache
  script:
    - ./ci-gradle.sh assemble
  after_script:
    - ./ci-gradle-cleanup.sh

test:
  stage: test
  extends:
    - .cache
  script:
    - ./ci-gradle.sh test
    - bash <(curl -s https://codecov.io/bash)
  after_script:
    - ./ci-gradle-cleanup.sh
  artifacts:
    when: always
    reports:
      junit: "**/build/test-results/test/**/TEST-*.xml"
  needs:
    - build

deploy:
  stage: deploy
  extends:
    - .cache
  script:
    - ./ci-gradle.sh version deploy closeStagingRepo
  after_script:
    - ./ci-gradle-cleanup.sh
