.cache:
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    policy: pull-push
    paths:
      - build
      - .gradle

image: azul/zulu-openjdk:14

stages:
  - build
  - test
  - deploy

build:
  stage: build
  extends:
    - .cache
  script:
    - ./ci-build.sh
  after_script:
    - ./ci-gradle-cleanup.sh

.test:
  stage: test
  extends:
    - .cache
  script:
    - ./ci-test.sh
  after_script:
    - ./ci-gradle-cleanup.sh
  artifacts:
    when: always
    reports:
      junit: "**/build/test-results/test/**/TEST-*.xml"
  needs:
    - build

deploy:
  stage: deploy
  extends:
    - .cache
  script:
    - ./ci-deploy.sh
  after_script:
    - ./ci-gradle-cleanup.sh
