.generate-dsl-openshift:
  stage: dsls
  script:
    - |
      cd kuberig-dsl/vanilla-dsls/kuberig-dsl-openshift/kuberig-dsl-openshift-$OPENSHIFT_VERSION
      source ../../../../ci-gradle-init.sh
      gradle publishToMavenLocal
  needs:
    - kuberig-dsl-deploy
    

