name: GitHub CI

on: [push]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Install Java
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: build
        run: |
          ./ci-build.sh
#      - name: test
#        run: |
#          ./ci-test.sh
      - name: deploy
        run: |
          ./ci-deploy.sh